;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; anything.el
;; INSTALL
;; (auto-install-batch "anithing")
;; (install-elisp-from-emacswiki "color-moccur.el")
;; (install-elisp "http://svn.coderepos.org/share/lang/elisp/anything-c-moccur/trunk/anything-c-moccur.el")

(require 'anything-config)

(define-key anything-map (kbd "C-M-n") 'anything-next-source)
(define-key anything-map (kbd "C-M-p") 'anything-previous-source)

(defun my-anything ()
  "Anything command for you.

It is automatically generated by `anything-migrate-sources'."
  (interactive)
  (anything-other-buffer
    '(anything-c-source-buffers+
      anything-c-source-recentf
      anything-c-source-files-in-current-dir+
      anything-c-source-file-name-history
      anything-c-source-occur
      anything-c-source-locate
      anything-c-source-info-pages
      anything-c-source-info-elisp
      anything-c-source-man-pages
      anything-c-source-emacs-commands)
    "*my-anything*"))

(require 'color-moccur)
;; 複数の検索語や、特定のフェイスのみマッチ等の機能を有効にする
;; 詳細は http://www.bookshelf.jp/soft/meadow_50.html#SEC751
(setq moccur-split-word t)

;; migemoがrequireできる環境ならmigemoを使う
(when (require 'migemo nil t) ;第三引数がnon-nilだとloadできなかった場合にエラーではなくnilを返す
  (setq moccur-use-migemo t))

(require 'anything-c-moccur)
;; カスタマイズ可能変数の設定(M-x customize-group anything-c-moccur でも設定可能)
(setq
 anything-c-moccur-anything-idle-delay 0.2
 ;;"anything-c-moccur-dmoccur"などのコマンドでバッファの情報をハイライトする
 anything-c-moccur-higligt-info-line-flag t
 ;;現在選択中の候補の位置を他のwindowに表示する
 anything-c-moccur-enable-auto-look-flag t
 ;;"anything-c-moccur-occur-by-moccur'の起動時にポイントの位置の単語を初期パターンにする
 anything-c-moccur-enable-initial-pattern t
 )

(global-set-key (kbd "C-:") 'my-anything)
(global-set-key (kbd "M-y") 'anything-show-kill-ring)
(global-set-key (kbd "M-o") 'anything-c-moccur-occur-by-moccur)
(global-set-key (kbd "C-M-o") 'anything-c-moccur-dmoccur)

(add-hook 'dired-mode-hook
          '(lambda ()
             (local-set-key (kbd "O") 'anything-c-moccur-dired-do-moccur-by-moccur)))

;; M-x install-elisp-from-emacswiki anything-grep.el
(require 'anything-grep)
(setq anything-grep-alist
      '(("org-files" ("egrep -Hin %s *" "~/.org"))
        ("buffers" ("egrep -Hin %s $buffers" "/"))
        ))
